### PR TITLE
As per email query

### PR DESCRIPTION
**Pull request by oxfpete**
The board file ending with waive is the version I am currently tidying up assuming we are safe to route like this.

### CODE REVIEW

**Comment by DavidCussans** [comment]
Pete,

Putting the vias there is fine.

Putting the level shifters under the SFP cages means that we will need to find cages that can be soldered. With components under the SFPs we won't be able to use press-fit pins.

Cheers!
   David

Dr David Cussans                    University of Bristol,
office: +44-(117)-95 46879   H.H. Wills Physics Laboratory,
     lab: +44-(117)-33 17199   Tyndall Avenue,
     fax: +44-(117)-925 5624   Bristol BS8 1TL, UK
________________________________
From: Peter Hastings ***@***.***>
Sent: Tuesday, May 21, 2024 3:55 PM
To: uob-hep-cad/uob-hep-pc065 ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [uob-hep-cad/uob-hep-pc065] As per email query (PR #42)


The board file ending with waive is the version I am currently tidying up assuming we are safe to route like this.

________________________________
You can view, comment on, or merge this pull request online at:

  https://github.com/uob-hep-cad/uob-hep-pc065/pull/42

Commit Summary

  *   f38753d<https://github.com/uob-hep-cad/uob-hep-pc065/pull/42/commits/f38753d42abbd4f0bcf8a26f18e92bb8ba50909d> internal signal layers modifed to free up space for level shifters
  *   4c0ab85<https://github.com/uob-hep-cad/uob-hep-pc065/pull/42/commits/4c0ab85acb09a0cb5ee970a41a4cd64c5bdd2120> I am not too happy about saying this but...
  *   6ce5a6c<https://github.com/uob-hep-cad/uob-hep-pc065/pull/42/commits/6ce5a6c1bb195980044a0a882680bf48f8022950> query about via under sfp cages

File Changes

(9 files<https://github.com/uob-hep-cad/uob-hep-pc065/pull/42/files>)

  *   M design_files/worklib/pc065b_fibv2_toplevel/physical/allegro.jrl<https://github.com/uob-hep-cad/uob-hep-pc065/pull/42/files#diff-cffb2247f92651d0f0a4c5ff17b7999bbe28549133c53fb85455606572b0132d> (2273)
  *   M design_files/worklib/pc065b_fibv2_toplevel/physical/allegro.jrl,1<https://github.com/uob-hep-cad/uob-hep-pc065/pull/42/files#diff-c64012be6bad0865e5df71e91dabf70639795ce889c563b6118b39712f3417ba> (11705)
  *   M design_files/worklib/pc065b_fibv2_toplevel/physical/batch_drc.log<https://github.com/uob-hep-cad/uob-hep-pc065/pull/42/files#diff-ff152d4bbe47339a0d1ceb2425808d9fdae883c80119fce8828028bd9dc356b4> (6)
  *   M design_files/worklib/pc065b_fibv2_toplevel/physical/batch_drc.log,1<https://github.com/uob-hep-cad/uob-hep-pc065/pull/42/files#diff-17345210197d83686993e066584b656fb780c0d98348c635c12fdedd97b6b670> (6)
  *   M design_files/worklib/pc065b_fibv2_toplevel/physical/batch_drc.log,2<https://github.com/uob-hep-cad/uob-hep-pc065/pull/42/files#diff-2ece527b5e2cf872da89ad11b0f8d23230510e40515f4debac7b8b9c1f8e9115> (6)
  *   M design_files/worklib/pc065b_fibv2_toplevel/physical/batch_drc.log,3<https://github.com/uob-hep-cad/uob-hep-pc065/pull/42/files#diff-12559ae647093c1526b1d9fe5e11e287b0837155757d1e23fb23d7758f26277c> (6)
  *   M design_files/worklib/pc065b_fibv2_toplevel/physical/master.tag<https://github.com/uob-hep-cad/uob-hep-pc065/pull/42/files#diff-5e91b1bda8b3bb64deb743879dbdb238b1b641aa45d795f8b0811434d03d7a72> (2)
  *   M design_files/worklib/pc065b_fibv2_toplevel/physical/pc065c_fibv2_toplevel_26.brd<https://github.com/uob-hep-cad/uob-hep-pc065/pull/42/files#diff-1ef0c2a7b934bda1cbecdd0aea58f61b22b62047c26c0c94b4624c1a51a89fdb> (0)
  *   A design_files/worklib/pc065b_fibv2_toplevel/physical/pc065c_fibv2_toplevel_26_waive.brd<https://github.com/uob-hep-cad/uob-hep-pc065/pull/42/files#diff-b13d054d8d5f6f0ff06c161ff64c732bc1fc7bf6599d44ce02d214ad715f9bbe> (0)

Patch Links:

  *   https://github.com/uob-hep-cad/uob-hep-pc065/pull/42.patch
  *   https://github.com/uob-hep-cad/uob-hep-pc065/pull/42.diff

**Comment by oxfpete** [comment]
Oh crap, did you want me to position them away from that area? I don’t know about availability of SFP cage styles.

**Comment by DavidCussans** [comment]
Pete,

Probably fine. We can use SFP cages that need soldering, rather than press-fit.

I think TE CONNECTIVITY 1658744-3 might work ( rather than the TYCO 2007132-1 , which has push-fit mounting pins ). Just need to check the position of the mounting pins.

Cheers!
   David

Dr David Cussans                    University of Bristol,
office: +44-(117)-95 46879   H.H. Wills Physics Laboratory,
     lab: +44-(117)-33 17199   Tyndall Avenue,
     fax: +44-(117)-925 5624   Bristol BS8 1TL, UK
________________________________

**Comment by DavidCussans** [comment]
Pete,

That should have been "I think the TE 1658723-2 might work"

... but are the pins in the same place....

Could you take a look at the data-sheets and/or buy a sample of each and take a look...

David

Dr David Cussans                    University of Bristol,
office: +44-(117)-95 46879   H.H. Wills Physics Laboratory,
     lab: +44-(117)-33 17199   Tyndall Avenue,
     fax: +44-(117)-925 5624   Bristol BS8 1TL, UK
________________________________

**Comment by oxfpete** [comment]
Just out of interest do you think those LED indicators will be an issue with the press cage too? What I mean is are we stressing about a non issue?

I will have a look at that datasheet and compare too. There is possibly room at the bottom edge of the card to move those level shifters, I was trying to keep the escapes clear from that FMC connector.

Watch this space 😊

**Pull request merged**
