### PR TITLE
uncovered vias and tidying

### PR DESCRIPTION
**Pull request by oxfpete**
as per title

### CODE REVIEW

**Comment by DavidCussans** [comment]
Pete,

Thanks for the PR. I have merged it.

However, I can't see the uncovered vias , or the extra vias/test-points to give access to the clock lines.

Are you sure you have committed all the files in your local version?

Cheers!
  David

Dr David Cussans                    University of Bristol,
office: +44-(117)-95 46879   H.H. Wills Physics Laboratory,
     lab: +44-(117)-33 17199   Tyndall Avenue,
     fax: +44-(117)-925 5624   Bristol BS8 1TL, UK
________________________________
From: Peter Hastings ***@***.***>
Sent: Monday, June 3, 2024 11:04 AM
To: uob-hep-cad/uob-hep-pc065 ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [uob-hep-cad/uob-hep-pc065] uncovered vias and tidying (PR #48)


as per title

________________________________
You can view, comment on, or merge this pull request online at:

  https://github.com/uob-hep-cad/uob-hep-pc065/pull/48

Commit Summary

  *   8f04283<https://github.com/uob-hep-cad/uob-hep-pc065/pull/48/commits/8f042838611e8e9aa9d9c320ea3a76926a14f756> uncovered vias and tidying

File Changes

(19 files<https://github.com/uob-hep-cad/uob-hep-pc065/pull/48/files>)

  *   M design_files/worklib/pc065b_fibv2_toplevel/physical/allegro.jrl<https://github.com/uob-hep-cad/uob-hep-pc065/pull/48/files#diff-cffb2247f92651d0f0a4c5ff17b7999bbe28549133c53fb85455606572b0132d> (7837)
  *   M design_files/worklib/pc065b_fibv2_toplevel/physical/allegro.jrl,1<https://github.com/uob-hep-cad/uob-hep-pc065/pull/48/files#diff-c64012be6bad0865e5df71e91dabf70639795ce889c563b6118b39712f3417ba> (13159)
  *   M design_files/worklib/pc065b_fibv2_toplevel/physical/batch_drc.log<https://github.com/uob-hep-cad/uob-hep-pc065/pull/48/files#diff-ff152d4bbe47339a0d1ceb2425808d9fdae883c80119fce8828028bd9dc356b4> (4)
  *   M design_files/worklib/pc065b_fibv2_toplevel/physical/batch_drc.log,1<https://github.com/uob-hep-cad/uob-hep-pc065/pull/48/files#diff-17345210197d83686993e066584b656fb780c0d98348c635c12fdedd97b6b670> (4)
  *   M design_files/worklib/pc065b_fibv2_toplevel/physical/batch_drc.log,2<https://github.com/uob-hep-cad/uob-hep-pc065/pull/48/files#diff-2ece527b5e2cf872da89ad11b0f8d23230510e40515f4debac7b8b9c1f8e9115> (6)
  *   M design_files/worklib/pc065b_fibv2_toplevel/physical/batch_drc.log,3<https://github.com/uob-hep-cad/uob-hep-pc065/pull/48/files#diff-12559ae647093c1526b1d9fe5e11e287b0837155757d1e23fb23d7758f26277c> (6)
  *   M design_files/worklib/pc065b_fibv2_toplevel/physical/downrev.log<https://github.com/uob-hep-cad/uob-hep-pc065/pull/48/files#diff-6dc3d11fa0b14f957890945c2f8408943178fbcf21a53ec7b478105f445166ca> (4)
  *   M design_files/worklib/pc065b_fibv2_toplevel/physical/downrev.log,1<https://github.com/uob-hep-cad/uob-hep-pc065/pull/48/files#diff-ca385c8b913a662e461c7f88eae7c01c244018d08f19ffba5edd71900ff41cbc> (4)
  *   M design_files/worklib/pc065b_fibv2_toplevel/physical/downrev.log,2<https://github.com/uob-hep-cad/uob-hep-pc065/pull/48/files#diff-c3952ad6283f90aafba7a5e8a747adb3bad911a891bb9164cbcb64aa754a28b4> (4)
  *   M design_files/worklib/pc065b_fibv2_toplevel/physical/downrev.log,3<https://github.com/uob-hep-cad/uob-hep-pc065/pull/48/files#diff-510db4998abc7a2ebe800a7191c2e2cba22260767fc762d5b9324240cbda92db> (4)
  *   M design_files/worklib/pc065b_fibv2_toplevel/physical/extract.log,1<https://github.com/uob-hep-cad/uob-hep-pc065/pull/48/files#diff-5de61862220b19adf06b4e830fdae138eff1a4f4c314e081ad9c703e56439ea9> (48)
  *   M design_files/worklib/pc065b_fibv2_toplevel/physical/extract.log,2<https://github.com/uob-hep-cad/uob-hep-pc065/pull/48/files#diff-0926459e4c7ba2aac6ac523b852fc44b709adb14563a580a4c1c04a38c85e25d> (35)
  *   M design_files/worklib/pc065b_fibv2_toplevel/physical/master.tag<https://github.com/uob-hep-cad/uob-hep-pc065/pull/48/files#diff-5e91b1bda8b3bb64deb743879dbdb238b1b641aa45d795f8b0811434d03d7a72> (2)
  *   M design_files/worklib/pc065b_fibv2_toplevel/physical/padstack_editor.jrl<https://github.com/uob-hep-cad/uob-hep-pc065/pull/48/files#diff-4dd042107da6aa4ffffb515ac1f882fba9d596cdc9c237eaef864690ae210144> (248)
  *   M design_files/worklib/pc065b_fibv2_toplevel/physical/padstack_editor.jrl,1<https://github.com/uob-hep-cad/uob-hep-pc065/pull/48/files#diff-663e49cd0f3f30f0dea1ce8e5395eb1895591cad77ec1bdf79cdf67eb5f7f59d> (32)
  *   M design_files/worklib/pc065b_fibv2_toplevel/physical/pc065c_fibv2_toplevel_27.brd<https://github.com/uob-hep-cad/uob-hep-pc065/pull/48/files#diff-c3c40d4ddd9f54ced50ca243c90510d9e397f20b793d439146ec6cc11923a965> (0)
  *   A design_files/worklib/pc065b_fibv2_toplevel/physical/pc065c_fibv2_toplevel_28.brd<https://github.com/uob-hep-cad/uob-hep-pc065/pull/48/files#diff-27e2a557db2ece2b3c22444425cdbf9415293f7a91123eb5921dbe073a12b02b> (0)
  *   A design_files/worklib/pc065b_fibv2_toplevel/physical/refresh_padstack.log<https://github.com/uob-hep-cad/uob-hep-pc065/pull/48/files#diff-2513a7ef4b1b9097bbf09d7c0d528e56ffa8620bf05611d20d6fc48cfa496c84> (601)
  *   A design_files/worklib/pc065b_fibv2_toplevel/physical/via22rd0-3d_open.pad<https://github.com/uob-hep-cad/uob-hep-pc065/pull/48/files#diff-327527ab41bdabb0a6b42988440aeac1d694e0bd35057b5f80ecc5ea667aa66f> (0)

Patch Links:

  *   https://github.com/uob-hep-cad/uob-hep-pc065/pull/48.patch
  *   https://github.com/uob-hep-cad/uob-hep-pc065/pull/48.diff

**Comment by oxfpete** [comment]
Hi David

The uncovered vias are visible if you select the “LSM2”  view – the bottom soldermask. I have uncovered the vias for the clocks/data lines and a few ground vias nearby.
***@***.***

In the artwork creation menu I have modified the solder mask for the bottom layer to include the soldermask defined in a custom through via. When the Gerber data is generated these will be exposed as there will be no resist on them.

***@***.***

Cheers
Pete

**Comment by oxfpete** [comment]
Hi David

What is the maximum clock frequency on this layout? Are we safe to add vias that go nowhere?

Cheers
Pete

**Comment by DavidCussans** [comment]
Pete,

The clock frequency is 250MHz. So, yes, as long as the vias are positioned "in" the tracks, it will be OK to add vias as test-points on the clock tracks.

Obviously don't add huge vias. The same size as the ones on the TD_FFD_{P,N}<7..0> will be fine.

Add some uncovered vias connected to ground near the uncovered clock/data vias. I will be using differential probes, but I always like to have a short ground connection...

Cheers!
   David

Dr David Cussans                    University of Bristol,
office: +44-(117)-95 46879   H.H. Wills Physics Laboratory,
     lab: +44-(117)-33 17199   Tyndall Avenue,
     fax: +44-(117)-925 5624   Bristol BS8 1TL, UK

________________________________

**Comment by DavidCussans** [comment]
Pete,

The result of Pull Request #50 looks good.

Could you get quotes for fabrication of 6 PCBs and assembly of two?

I think the order will be placed by RAL PPD staff, so we should be off the hook for that.

Cheers!
   David

Dr David Cussans                    University of Bristol,
office: +44-(117)-95 46879   H.H. Wills Physics Laboratory,
     lab: +44-(117)-33 17199   Tyndall Avenue,
     fax: +44-(117)-925 5624   Bristol BS8 1TL, UK
________________________________

**Pull request merged**
